action_selector: "continuous"
epsilon_start: 0.3
epsilon_finish: 0.03
epsilon_anneal_time: 500000

runner: "episode"

buffer_size: 50
batch_size_run: 1
batch_size: 1

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0003

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac_continuous"
agent: "rnn_ns"
agent_output_type: "continuous"
learner: "actor_critic_pd_learner_continuous"
entropy_coef: 0.01
use_rnn: False
standardise_returns: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "centralV_pd_ns_continuous"

name: "maa2c_pd_ns_continuous"