env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null
  constraint_type: "test123"

test_greedy: True
test_nepisode: 50
test_interval: 5000
log_interval: 5000
runner_log_interval: 1000
learner_log_interval: 10000
t_max: 2050000
