env: "continuous_env"

env_args:
  key: "gridworld.scenarios.test_example:MultiBuilding-v0"
  time_limit: 25
  pretrained_wrapper: null
  constraint_type: "expectation"

test_greedy: True
test_nepisode: 50
test_interval: 5000
log_interval: 5000
runner_log_interval: 1000
learner_log_interval: 10000
t_max: 1000000
